server:
  port: 8200
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
    # 网关转发配置
    gateway:
      server:
        webflux:
          routes:
            - id: borrow-service        # 路由名称
              uri: lb://borrow-service   # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
              predicates:               # 路由规则，断言什么请求会被路由
                - Path=/borrow/**       # 只要是访问的这个路径，一律都被路由到上面指定的服务
                # 继续添加新的路由配置，这里就以书籍管理服务为例
                # 注意-要对齐routes:
            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/book/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
              filters: # 添加过滤器
                - AddRequestHeader=Test, HelloWorld!