#server:
#  port: 8103
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scdemo
    username: root
    password: zjh6851265
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
#eureka:
#  client:
#    # 将两个Eureka的地址都加入，这样就算有一个Eureka挂掉，也能完成注册
#    service-url:
#      defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka